theme: jekyll-theme-architect
title: Audate Search
description: Voice Search for the Browser.
show_downloads: true
github:
  zip_url: https://chrome.google.com/webstore/detail/audate-voice-search/agmgoemhckhccgibmoigonndjhjllcoh
  tar_url: https://chrome.google.com/webstore/detail/audate-voice-search/agmgoemhckhccgibmoigonndjhjllcoh
